// GENERATED by scripts/generate-env.ts — do not edit.
// Source: root .env (allowlisted PUBLIC_KEYS). Regenerate: `bun run env:generate`.
export const environment = {
  apiUrl: "",
  appName: "",
} as const;
