import { t } from 'elysia';
import { enumSchema } from '#project/elysia';
import { USER_ROLES, USER_STATUS_FILTERS, USER_STATUSES } from './users.types';

const nullableString = t.Union([t.String(), t.Null()]);

/**
 * The role list is the single source of truth for the create and update forms:
 * it matches the CHECK constraint on "user"."users".role, reaches the client
 * through the generated SDK types, and is echoed in the list response options.
 *
 * `enumSchema` rather than `t.UnionEnum`: the latter carries a default of the
 * first value, which Elysia would fill in for an absent optional property, so a
 * PATCH sending only a name would silently set the role to admin.
 */
export const userRoleSchema = enumSchema(USER_ROLES);
export const userStatusSchema = enumSchema(USER_STATUSES);
const userStatusFilterSchema = enumSchema(USER_STATUS_FILTERS);

const reasonSchema = t.String({ minLength: 3, maxLength: 500 });

export const usersStatusResponse = t.Object({
  service: t.String(),
  status: t.Literal('ok'),
  module: t.Literal('users'),
});

export const userResponse = t.Object({
  id: t.String({ format: 'uuid' }),
  name: t.String(),
  email: t.String(),
  role: userRoleSchema,
  status: userStatusSchema,
  emailVerifiedAt: nullableString,
  suspendedAt: nullableString,
  blockedAt: nullableString,
  deletedAt: nullableString,
  createdAt: t.String(),
  updatedAt: nullableString,
});

export const usersListQuery = t.Object({
  search: t.Optional(t.String({ maxLength: 255 })),
  status: t.Optional(userStatusFilterSchema),
  page: t.Optional(t.String({ maxLength: 8 })),
});

export const usersListResponse = t.Object({
  data: t.Array(userResponse),
  meta: t.Object({
    page: t.Integer(),
    perPage: t.Integer(),
    total: t.Integer(),
    totalPages: t.Integer(),
  }),
  filters: t.Object({
    search: t.String(),
    status: userStatusFilterSchema,
  }),
  options: t.Object({
    roles: t.Array(userRoleSchema),
    statuses: t.Array(userStatusSchema),
  }),
});

export const userIdParams = t.Object({ id: t.String({ format: 'uuid' }) });

/**
 * The id is generated by the Angular client as a UUIDv7 and sent with the
 * create request, so it is untrusted input: the format is validated here and
 * the database CHECK constraint rejects any non v7 uuid that slips through.
 */
export const createUserBody = t.Object({
  id: t.String({ format: 'uuid' }),
  name: t.String({ minLength: 1, maxLength: 255 }),
  email: t.String({ format: 'email', minLength: 3, maxLength: 255 }),
  role: userRoleSchema,
});

/** Email is deliberately absent: it cannot be changed through the API. */
export const updateUserBody = t.Object({
  name: t.Optional(t.String({ minLength: 1, maxLength: 255 })),
  role: t.Optional(userRoleSchema),
});

export const statusActionBody = t.Object({ reason: reasonSchema });
